version: '2'
services:
  eth:
    build: monitored-geth-client
    restart: on-failure
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      # - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --mine --minerthreads=2 --rpccorsdomain="*" --rpcaddr="0.0.0.0" --networkid=456719 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@192.168.31.245:30303"'
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    # volumes:
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"